Repository ServiceNow/azimuth, pull requests merged in 2022-08, with the labels that each got.

#160 Update python dependencies
  azimuth/app.py
  poetry.lock
  pyproject.toml
Labels: python

#207 Work around max page size
  CHANGELOG.md
  webapp/src/components/Controls/Controls.tsx
  webapp/src/components/Metrics/PerformanceAnalysis.tsx
  webapp/src/components/Table.tsx
Labels: javascript

#226 Fix log level ignored in app.py
  azimuth/app.py
Labels: bug
